version: '3.6'
services:
  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    image: 'postgres:11-alpine'
    restart: always
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
  web:
    build: .
    depends_on:
      - db
    environment:
      MIX_ENV: dev
    env_file:
      - .env
    ports:
      - '4000:4000'
    volumes:
      - .:/app
volumes:
  pgdata:

# https://dev.to/hlappa/development-environment-for-elixir-phoenix-with-docker-and-docker-compose-2g17
# DATABASE_URL=postgres://postgres:postgres@db:5432/myapp_dev
# docker-compose build
# docker-compose run web mix ecto.create
# docker-compose up
# docker ps
## Configure your database
# config :myapp, Myapp.Repo,
#  url: System.get_env("DATABASE_URL"),
#  show_sensitive_data_on_connection_error: true,
#  pool_size: 10

# other useful docker commands
# docker stop eb4
# docker rm eb4
# docker exec -it <mycontainer> bash
# iex -S mix phx.server

    #command: mix deps.get && mix phx.server

# multiple commands      
#    command: >
#      bash -c "python manage.py migrate
#      && python manage.py runserver 0.0.0.0:8000"